## 난수 발생과 카운팅 - 시드 설정

컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아니다. 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성한다. 이런 시작 숫자를 시드(seed)라고 한다. 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 된다. 따라서 시드값은 한 번만 정해주면 된다. 시드는 보통 현재 시각등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있다. 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있다. 이 책에서는 코드의 결과를 재현하기 위해 항상 시드를 설정한다.

In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [4]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [5]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [6]:
np.random.seed(0)

In [7]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [8]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [9]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

## 데이터의 순서 바꾸기

In [11]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.random.shuffle(x)
x

array([5, 7, 6, 1, 9, 3, 0, 2, 8, 4])

## 데이터 샘플링

이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것을 표본선택 혹은 샘플링(sampling)이라고 한다. 샘플링에는 choice 함수를 사용한다. choice 함수는 다음과 같은 인수를 가질 수 있다.

numpy.random.choice(a, size=None, replace=True, p=None)

a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성

size : 정수. 샘플 숫자

replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능

p : 배열. 각 데이터가 선택될 수 있는 확률

In [17]:
np.random.choice(5,5,replace=False) # shuffle 명령과 같다

array([4, 2, 3, 1, 0])

In [22]:
np.random.choice(5,3,replace=False) # 5개 숫자 중 3개 선택

array([1, 2, 4])

In [23]:
np.random.choice(5,10) # 반복해서 10개 선택

array([0, 4, 3, 2, 0, 1, 1, 3, 0, 0])

In [25]:
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0]) # 선택 확률을 다르게 해서 10개 선택

array([2, 3, 3, 3, 3, 2, 3, 3, 3, 3])

## 난수 생성

넘파이의 random 서브패키지는 이외에도 난수를 생성하는 다양한 함수를 제공한다. 그 중 가장 간단하고 많이 사용되는 것은 다음 3가지 함수다.

rand: 0부터 1사이의 균일 분포

randn: 표준 정규 분포

randint: 균일 분포의 정수 난수

In [26]:
np.random.randn(10)

array([ 0.42830357,  0.99627783, -0.49114966,  0.71267817,  1.11334035,
       -2.15367459, -0.41611148, -1.07089699,  0.22113881, -1.12305712])

In [27]:
np.random.randn(3,5)

array([[-1.05075796,  1.01207905,  1.54371643, -0.40211489,  0.8647491 ],
       [-0.22686923,  0.81116027,  0.28779461, -0.53846816,  1.9084621 ],
       [-0.475776  ,  1.44073112, -1.14907568,  0.80571455,  1.75610703]])

numpy.random.randint(low, high=None, size=None)

만약 high를 입력하지 않으면 0과 low사이의 숫자를, high를 입력하면 low와 high는 사이의 숫자를 출력한다. size는 난수의 숫자이다.

In [28]:
np.random.randint(10, size=10)

array([5, 3, 1, 8, 0, 4, 9, 6, 5, 7])

In [29]:
np.random.randint(10,20,size=10)

array([18, 18, 19, 12, 18, 16, 16, 19, 11, 16])

In [31]:
np.random.randint(10,20,size=(3,5))

array([[18, 18, 13, 12, 13],
       [16, 13, 16, 15, 17],
       [10, 18, 14, 16, 15]])

## 연습 문제
동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.

주사위를 100번 던져서 나오는 숫자의 평균을 구하라.

In [38]:
np.random.choice(2,10)

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 1])

In [45]:
a = np.random.randint(1,6,size=100)
a

array([1, 4, 1, 3, 2, 1, 5, 1, 4, 5, 5, 2, 1, 3, 5, 5, 3, 5, 4, 3, 4, 1,
       1, 1, 4, 5, 5, 3, 3, 5, 2, 4, 4, 4, 2, 3, 3, 4, 3, 4, 5, 5, 3, 2,
       3, 1, 4, 1, 3, 5, 4, 3, 2, 3, 2, 5, 2, 1, 1, 1, 1, 1, 2, 1, 4, 2,
       5, 2, 3, 5, 1, 1, 3, 1, 5, 5, 5, 2, 2, 5, 2, 2, 4, 2, 4, 4, 2, 2,
       2, 1, 4, 1, 5, 2, 5, 1, 4, 3, 2, 5])

In [46]:
np.mean(a)

2.97

가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라



In [49]:
y = np.random.seed(10000)

In [50]:
y = np.random.randn(250)

In [52]:
print(y)

[-1.27109064  0.17613707 -0.29621638  0.32692882 -0.97341942  0.227681
 -0.81932804  0.10722255  0.97527763  0.08197388 -0.47662253 -1.49217154
 -0.40346495  0.69477827  0.2121528   0.09098984 -1.54885465 -0.04482736
  1.55676333  1.94711068 -0.78514011 -2.13921194 -1.26425853  0.29498718
  0.80648927  0.27767032 -1.24384504  0.78727437  0.75203041  0.17298001
 -0.73783565  0.96919093 -0.64637056  1.81109463 -0.99044486 -1.36911291
  0.07248481  0.40832729  0.1687738  -0.58670124 -1.51733757  0.72040884
 -2.14986374 -1.23310196 -0.12122475  0.68214936  1.26832604 -0.02907836
 -0.80203131  0.67907827 -1.04111161  0.93386042  0.34352489  1.78771666
  0.48640788  0.46039938 -0.83387849  0.04040953 -0.09290729 -0.75064297
 -0.37392144  0.3453563   0.49987149 -1.1674225  -0.38700182 -0.96593647
 -2.36935061  1.11943353  1.14754071  1.1925147   0.41127294  0.62608869
  0.04526669  0.96049828 -0.29280139  0.01127911  0.80587441 -0.866476
 -1.04311829  0.57402145  1.07180389 -0.32848638 -0.381

## 정수 데이터 카운팅
이렇게 발생시킨 난수가 실수값이면 히스토그램 등을 사용하여 분석하면 된다. 히스토그램을 시각화 부분에서 나중에 자세히 설명한다.

만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석할 수 있다.

unique

unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력한다. return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력한다.



In [54]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [55]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [56]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [57]:
count

array([2, 2, 1], dtype=int64)

그러나 unique 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않는다. 예를 들어 주사위를 10번 던졌는데 6이 한 번도 나오지 않으면 이 값을 0으로 세어주지 않는다.

따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 bincount 함수에 minlength 인수를 설정하여 쓰는 것이 더 편리하다. bincount 함수는 0 부터 minlength - 1 까지의 숫자에 대해 각각 카운트를 한다. 데이터가 없을 경우에는 카운트 값이 0이 된다.

In [58]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)