In [1]:
import numpy as np

## 1차원 배열 만들기

In [2]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

## 벡터화 연산

In [4]:
# 여러개의 데이터를 모두 2배 해야하는 경우

data = [0,1,2,3,4,5,6,7,8,9] # 리스트는 아래처럼 반복문 돌려야 2배가됨

answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
2 * x # 배열은 그냥 곱하면 됨

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
y = np.array([0,1,2,3,4,5,6,7,8,9])
2 * x + y

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [15]:
print(x == 2)
print(y > 5)
print((x == 3 )&(y > 1))

[False False  True False False False False False False False]
[False False False False False False  True  True  True  True]
[False False False  True False False False False False False]


## 2차원 배열 만들기

In [16]:
# ndarray는 N-dimensional Array의 약자
# 행렬은 matrix라고 함.

c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
# 행의 갯수
len(c)

2

In [18]:
# 열의 갯수
len(c[0])

3

In [19]:
d = np.array([[10,20,30,40],[50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열 만들기

In [20]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [21]:
len(d),len(d[0]),len(d[0][0])

(2, 3, 4)

## 배열의 차원과 크기 알아내기

In [24]:
# 배열의 차원 = ndim, 배열의 크기 = shape 
a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [25]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


## 배열의 인텍싱

In [26]:
a = np.array([0,1,2,3,4])
a[2]

2

In [27]:
a[-1]

4

In [28]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
a[0,0]

0

In [30]:
a[0,1]

1

In [31]:
a[-1,-1]

5

## 배열 슬라이싱

In [32]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
a[0,:]#첫번째 행 전체

array([0, 1, 2, 3])

In [34]:
a[:,1]# 두번째 열 전체

array([1, 5])

In [35]:
a[1,1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [36]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [43]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
m[1,2]

7

In [39]:
m[2,-1]

14

In [41]:
m[1,1:3]

array([6, 7])

In [44]:
m.ndim,m.shape

(2, (3, 5))

In [46]:
m[1:,2]

array([ 7, 12])

In [54]:
m[0,3:5],m[1,3:5]

(array([3, 4]), array([8, 9]))

## 배열 팬시 인덱싱(Fancy indexing)

In [55]:
# 짝수 = True, 홀수 = False
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False,True, False,True, 
                False,True, False,True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [58]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [59]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [60]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [61]:
a[a % 3 == 0]

array([0, 3, 6, 9])

In [62]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [63]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [64]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [66]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [67]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [113]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [112]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [121]:
x[(x%3==0)&(x%4==1)]

array([9])