In [4]:
import pandas as pd

## 시리즈 생성

In [2]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
             index = ["서울","부산","인천","대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [3]:
pd.Series(range(10,14))

0    10
1    11
2    12
3    13
dtype: int64

In [4]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [5]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [7]:
s.name = "인구"
s.index.name = "도시"
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

## 시리즈 연산

In [8]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

## 시리즈 인덱싱

In [9]:
s[1], s["부산"]

(3448737, 3448737)

In [10]:
s[3], s["대구"]

(2466052, 2466052)

In [11]:
s[[0,3,1]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [12]:
s[["서울","대구","부산"]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [13]:
s[(250e4 < s)&(s < 500e4)] # 인구가 250만 초과, 500만 미만

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [14]:
s[1:3]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [17]:
s["부산":"대구"]

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [19]:
s["부산":"부산"]

도시
부산    3448737
Name: 인구, dtype: int64

In [20]:
s0 = pd.Series(range(3), index=["a","b","c"])
s0

a    0
b    1
c    2
dtype: int64

In [21]:
s0.a

0

In [22]:
s0.b

1

## 시리즈와 딕셔너리 자료형
시리즈 객체는 라벨 값에 의해 인덱싱이 가능하므로 실질적으로 인덱스 라벨 값을 키(key)로 가지는 딕셔너리 자료형과 같다고 볼 수 있다. 따라서 딕셔너리 자료형에서 제공하는 in 연산도 가능하고 items 메서드를 사용하면 for 루프를 통해 각 원소의 키(key)와 값(value)을 접근할 수도 있다.

In [24]:
"서울" in s # 인텍스 라벨 중에 서울이 있는가

True

In [25]:
"대전" in s # 인텍스 라벨 중에 대전이 있는가

False

In [26]:
for k, v in s.items():
    print("%s = %d" %(k,v))

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [27]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [28]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
               index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

## 인텍스 기반 연산

이번에는 2015년도와 2010년의 인구 증가를 계산해 보자. 두 개의 시리즈의 차이를 구하면 된다. 두 시리즈에 대해 연산을 하는 경우 인덱스가 같은 데이터에 대해서만 차이를 구한다.

In [30]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [31]:
s.values - s2.values

array([ 6511121, -6182745,   258416,   975894], dtype=int64)

In [33]:
s.values, s2.values

(array([9904312, 3448737, 2890451, 2466052], dtype=int64),
 array([3393191, 9631482, 2632035, 1490158], dtype=int64))

In [34]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [35]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [37]:
rs = (s-s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

## 데이터 갱신, 추가, 삭제
인덱싱을 이용하면 딕셔너리처럼 데이터를 갱신(update)하거나 추가(add)할 수 있다.

In [39]:
rs["부산"] = 1.63
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [41]:
rs["대구"] = 1.41
rs

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64

In [44]:
del rs["서울"]

KeyError: '서울'

In [45]:
rs

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64

(1) 임의로 두 개의 시리즈 객체를 만든다. 모두 문자열 인덱스를 가져야 하며 두 시리즈에 공통적으로 포함되지 않는 라벨이 있어야 한다.

(2) 위에서 만든 두 시리즈 객체를 이용하여 사칙 연산을 한다.



In [47]:
a = pd.Series([21688,32168,35232,82345], index = ["아이폰","에어팟","맥북","아이패드"])
a

아이폰     21688
에어팟     32168
맥북      35232
아이패드    82345
dtype: int64

In [49]:
b = pd.Series([12345,67890,98765,43210], index = ["아이폰","마우스","맥북","아이패드"])
b

아이폰     12345
마우스     67890
맥북      98765
아이패드    43210
dtype: int64

In [50]:
a - b

마우스         NaN
맥북     -63533.0
아이패드    39135.0
아이폰      9343.0
에어팟         NaN
dtype: float64

In [51]:
a.values - b.values

array([  9343, -35722, -63533,  39135], dtype=int64)

In [52]:
a + b

마우스          NaN
맥북      133997.0
아이패드    125555.0
아이폰      34033.0
에어팟          NaN
dtype: float64

In [54]:
rs = (a - b) / b * 100
rs = rs[rs.notnull()]
rs

맥북     -64.327444
아이패드    90.569313
아이폰     75.682463
dtype: float64

## 데이터프레임 클래스

시리즈가 1차원 벡터 데이터에 행방향 인덱스(row index)를 붙인 것이라면 데이터프레임 DataFrame 클래스는 2차원 행렬 데이터에 인덱스를 붙인 것과 비슷하다. 2차원이므로 각각의 행 데이터의 이름이 되는 행 인덱스(row index) 뿐 아니라 각각의 열 데이터의 이름이 되는 열 인덱스(column index)도 붙일 수 있다.



## 데이터프레임 생성

In [5]:
data = {
    "2015" : [9904312, 3448737, 2890451, 2466052],
    "2010" : [9631482, 3393191, 2632035, 2431774],
    "2005" : [9762546, 3512547, 2517680, 2456016],
    "2000" : [9853972, 3655437, 2466338, 2473990],
    "지역" : ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율" : [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역","2015","2010","2005","2000","2010-2015 증가율"]
index = ["서울" , "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

시리즈와 마찬가지로 데이터만 접근하려면 values 속성을 사용한다. 열방향 인덱스와 행방향 인덱스는 각각 columns, index 속성으로 접근한다.

In [6]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [7]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [8]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [10]:
df.index.name = "도시"
df.columns.name = "특성"
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [20]:
apple = {
    "2017" : [120, 130, 140, 150, 160],
    "2018" : [180, 190, 200, 230, 240],
    "2019" : [15, 20, 30, 35, None],
    "2020" : [30, 40, 50 ,60, 70],
    "2021" : [10, 11, 12, 13, 14],
    "제품" : ["아이폰", "맥북", "에어팟", "아이패드", "매직팬슬"]
}
columns = ["제품", "2017","2018","2019","2020","2021"]
index = ["애플","애플","애플","애플","애플"]
df1 = pd.DataFrame(apple, index = index, columns = columns)
df1

제품  2017  2018  2019  2020  2021
애플   아이폰   120   180  15.0    30    10
애플    맥북   130   190  20.0    40    11
애플   에어팟   140   200  30.0    50    12
애플  아이패드   150   230  35.0    60    13
애플  매직팬슬   160   240   NaN    70    14

In [21]:
df1.values

array([['아이폰', 120, 180, 15.0, 30, 10],
       ['맥북', 130, 190, 20.0, 40, 11],
       ['에어팟', 140, 200, 30.0, 50, 12],
       ['아이패드', 150, 230, 35.0, 60, 13],
       ['매직팬슬', 160, 240, nan, 70, 14]], dtype=object)

In [22]:
df1.columns

Index(['제품', '2017', '2018', '2019', '2020', '2021'], dtype='object')

In [23]:
df1.index

Index(['애플', '애플', '애플', '애플', '애플'], dtype='object')

In [24]:
df1.index.name = "회사"
df1.columns.name = "특성"
df1

특성    제품  2017  2018  2019  2020  2021
회사                                    
애플   아이폰   120   180  15.0    30    10
애플    맥북   130   190  20.0    40    11
애플   에어팟   140   200  30.0    50    12
애플  아이패드   150   230  35.0    60    13
애플  매직팬슬   160   240   NaN    70    14

In [25]:
df.T # 전치

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

## 열 데이터의 갱신, 추가, 삭제

In [26]:
# '2010-2015 증가율' 이라는 이름의 열 추가
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [28]:
# '2005-2010 증가율'이라는 이름의 열추가
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] *100).round(2)
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [29]:
# '2010-2015 증가율'이라는 이름의 열 삭제
del df["2010-2015 증가율"]
df

KeyError: '2010-2015 증가율'

## 열 인덱싱

In [30]:
# 하나의 열만 인덱싱하면 시리즈가 반환된다
df["지역"]

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [31]:
df1["제품"]

회사
애플     아이폰
애플      맥북
애플     에어팟
애플    아이패드
애플    매직팬슬
Name: 제품, dtype: object

In [32]:
# 여러개의 열을 인덱싱하면 부분적인 데이터프레임이 반환된다.
df[["2010", "2015"]]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [33]:
# 2010 이라는 열을 반환하면서 데이터프레임 자료형을 유지
df[["2010"]]

특성     2010
도시         
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [34]:
type(df[["2010"]])

pandas.core.frame.DataFrame

In [36]:
df[0]

KeyError: 0

In [39]:
import numpy as np

In [41]:
df2 = pd.DataFrame(np.arange(12).reshape(3,4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [42]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int32

In [44]:
df2[[1,2]]

1   2
0  1   2
1  5   6
2  9  10

In [45]:
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

## 행 인덱싱

In [46]:
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [47]:
df[1:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           -3.4

In [48]:
df[1:3]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [49]:
df["서울":"부산"]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [51]:
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

## 개별 데이터 인덱싱
데이터프레임에서 열 라벨로 시리즈를 인덱싱하면 시리즈가 된다. 이 시리즈를 다시 행 라벨로 인덱싱하면 개별 데이터가 나온다.

In [52]:
df["2015"]["서울"]

9904312

In [53]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

In [56]:
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

(1) 모든 학생의 수학 점수를 시리즈로 나타낸다.

In [54]:
df["수학"]

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

(2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.

In [65]:
df[["국어","영어"]]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

(3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.

In [68]:
df["평균점수"] = ((df["국어"] + df["영어"] + df["수학"]) / 3).round(2)
df

국어  영어  수학   평균점수
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  80  40  70  63.33

(4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.

In [67]:
df["국어"]["방자"] = 80
df

C:\anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


국어  영어  수학   평균점수
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  80  40  70  46.67

In [69]:
df

국어  영어  수학   평균점수
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  80  40  70  63.33

(5) 춘향의 점수를 데이터프레임으로 나타낸다.

In [73]:
df[:1]

국어  영어  수학   평균점수
춘향  80  90  90  86.67

(6) 향단의 점수를 시리즈로 나타낸다.

In [74]:
df[2:3]

국어  영어  수학  평균점수
향단  70  60  80  70.0